site_name: K9 — Kind Kubernetes Lab
site_description: Laboratório local de Kubernetes com Kind
nav:
  - Home: index.md
plugins:
  - techdocs-core
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
      check_paths: true
